# // Copyright 2022 CeresDB Project Authors. Licensed under Apache-2.0.

version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
